### ISSUE TITLE
Save language when switching

### ISSUE THREAD

**Issue by patrickschaper** [AOEpeople/meals#518]
Sadly when the language is changed it is not persisted, so the every time I open the page the language is reset.

Example:
In my case the meals page always opens in English due to my system language but because the meal description is never as thorough as it is in German I always switch to German. 
The next time I visit the page I have to open the menu again (on my phone) or find the language switch in the footer to switch the language. This is especially annoying when you try to keep your tabs list clean by closing it when your done looking at the meals. 😅

Thanks for the great work!

**Comment by hacksch** [comment]
Hello Patrick, we will take care of it. Thanks for your report.
